### ISSUE TITLE
ERR_TIMED_OUT errors

### ISSUE THREAD

**Issue by jmks** [comby-tools/comby-ui#10]
Hey

Last week I was using comby.live fine, but this week I noticed it's not working.
It seems to be making an AJAX call on every keystroke, and they are all timing out.

![image](https://user-images.githubusercontent.com/4923990/65459681-649e6c80-de1e-11e9-9790-6d05bb239548.png)

**Comment by rvantonder** [comment]
Hi @jmks, yeah it does do a request on every keystroke to get that quick feedback. Sometimes the server gets jammed up a bit with requests but usually straightens out after 2-5 minutes when this happens. I'm going to have a look at cancelling/timing out stale requests a bit more aggressively (which shouldn't be too noticeable for the user, but should help get rid of the behavior we're seeing here).

**Comment by rvantonder** [comment]
Willl use comby-tools/comby/pull/110 and try a timeout of 1 or 2 seconds and see if it improves the experience.

**Comment by jmks** [comment]
Thanks. Just wanted to put it on your radar.

**Comment by rvantonder** [comment]
I appreciate that! Please reopen if this crops up again.
