### ISSUE TITLE
Documentation is not a link, can't open in a new window

### ISSUE THREAD

**Issue by abitrolly** [comby-tools/comby-ui#14]
I am using Firefox and to open documentation in a new tab, I need to open this tab manually, because the Documentation element is a button without link, and doesn't have standard context menu or react to shift-clicking. Minor inconvenience, but still.

**Comment by rvantonder** [comment]
Made it a link and it's live. Thanks. 
<img width="399" alt="Screen Shot 2020-01-21 at 7 45 06 PM" src="https://user-images.githubusercontent.com/888624/72861253-974e5980-3c86-11ea-9b73-92d8f17d9094.png">
